# Generated by Django 5.0.3 on 2024-04-04 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber_shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='crm.barbershop'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Barber',
        ),
    ]
