# Generated by Django 5.0.3 on 2024-04-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_appointment_barber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='address',
        ),
    ]
