# Generated by Django 5.0.3 on 2024-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
